export type CatalogOption = {
  code?: string;
  label: string;
  metadata?: Record<string, string>;
};

export const REGION_CATALOG: Array<{ code: string; name: string }> = [
  { code: "REGION_I", name: "Region I" },
  { code: "REGION_II", name: "Region II" },
  { code: "REGION_III", name: "Region III" },
  { code: "REGION_IVA", name: "Region IV-A" },
  { code: "REGION_IVB", name: "Region IV-B" },
  { code: "REGION_V", name: "Region V" },
  { code: "REGION_VI", name: "Region VI" },
  { code: "REGION_VII", name: "Region VII" },
  { code: "REGION_VIII", name: "Region VIII" },
  { code: "REGION_IX", name: "Region IX" },
  { code: "REGION_X", name: "Region X" },
  { code: "REGION_XI", name: "Region XI" },
  { code: "REGION_XII", name: "Region XII" },
  { code: "REGION_XIII", name: "Region XIII" },
  { code: "NCR", name: "NCR" },
  { code: "CAR", name: "CAR" },
  { code: "BARMM", name: "BARMM" },
];

export const PROVINCE_CATALOG: Record<string, string[]> = {
  REGION_I: ["Ilocos Norte", "Ilocos Sur", "La Union", "Pangasinan"],
  REGION_II: ["Batanes", "Cagayan", "Isabela", "Nueva Vizcaya", "Quirino"],
  REGION_III: ["Bataan", "Bulacan", "Nueva Ecija", "Pampanga", "Tarlac", "Zambales", "Aurora"],
  REGION_IVA: ["Batangas", "Cavite", "Laguna", "Quezon", "Rizal"],
  REGION_IVB: ["Marinduque", "Occidental Mindoro", "Oriental Mindoro", "Palawan", "Romblon"],
  REGION_V: ["Albay", "Camarines Norte", "Camarines Sur", "Catanduanes", "Masbate", "Sorsogon"],
  REGION_VI: ["Aklan", "Antique", "Capiz", "Iloilo", "Negros Occidental", "Guimaras"],
  REGION_VII: ["Bohol", "Cebu", "Negros Oriental", "Siquijor"],
  REGION_VIII: ["Eastern Samar", "Leyte", "Northern Samar", "Samar", "Southern Leyte", "Biliran"],
  REGION_IX: ["Zamboanga del Norte", "Zamboanga del Sur", "Zamboanga Sibugay"],
  REGION_X: ["Bukidnon", "Camiguin", "Lanao del Norte", "Misamis Occidental", "Misamis Oriental"],
  REGION_XI: ["Davao del Norte", "Davao del Sur", "Davao Oriental", "Davao de Oro", "Davao Occidental"],
  REGION_XII: ["Cotabato", "South Cotabato", "Sultan Kudarat", "Sarangani"],
  REGION_XIII: ["Agusan del Norte", "Agusan del Sur", "Surigao del Norte", "Surigao del Sur", "Dinagat Islands"],
  BARMM: ["Basilan", "Lanao del Sur", "Maguindanao", "Sulu", "Tawi-tawi"],
  CAR: ["Abra", "Benguet", "Ifugao", "Kalinga", "Mountain Province", "Apayao"],
  NCR: ["Metro Manila"],
};

export const ASSET_TYPE_ACCOUNT_CODES: Array<{ assetType: string; accountCode: string }> = [
  { assetType: "Agricultural and Forestry Equipment", accountCode: "10605040-00" },
  { assetType: "Airport Equipment", accountCode: "10605060-00" },
  { assetType: "Airport Systems", accountCode: "10603080-00" },
  { assetType: "Buildings", accountCode: "10604010-00" },
  { assetType: "Communication Equipment", accountCode: "10605070-00" },
  { assetType: "Communication Networks", accountCode: "10603060-00" },
  { assetType: "Construction and Heavy Equipment", accountCode: "10605080-00" },
  { assetType: "Disaster Response and Rescue Equipment", accountCode: "10605090-00" },
  { assetType: "Earthquake Rescue Equipment", accountCode: "10605090-03" },
  { assetType: "Firefighting Equipment and Accessories", accountCode: "10605090-01" },
  { assetType: "Flood and Rescue Equipment", accountCode: "10605090-02" },
  { assetType: "Flood Control Systems", accountCode: "10603020-00" },
  { assetType: "Historical Buildings", accountCode: "10611010-00" },
  { assetType: "Hospitals and Health Centers", accountCode: "10604030-00" },
  { assetType: "Hostels and Dormitories", accountCode: "10604060-00" },
  { assetType: "Information and Communication Technology Equipment", accountCode: "10605030-00" },
  { assetType: "Land", accountCode: "10601000-00" },
  { assetType: "Landslide Rescue Equipment", accountCode: "10605090-05" },
  { assetType: "Leased Assets, Buildings and Other Structures", accountCode: "10608020-00" },
  { assetType: "Leased Assets, Land", accountCode: "10608010-00" },
  { assetType: "Leased Assets, Machinery and Equipment", accountCode: "10608030-00" },
  { assetType: "Leased Assets, Transportation Equipment", accountCode: "10608040-00" },
  { assetType: "Machinery", accountCode: "10605010-00" },
  { assetType: "Marine and Fishery Equipment", accountCode: "10605050-00" },
  { assetType: "Markets", accountCode: "10604040-00" },
  { assetType: "Medical Equipment", accountCode: "10605110-00" },
  { assetType: "Military, Police and Security Equipment", accountCode: "10605100-00" },
  { assetType: "Office Equipment", accountCode: "10605020-00" },
  { assetType: "Other Heritage Assets", accountCode: "10611990-00" },
  { assetType: "Other Infrastructure Assets", accountCode: "10603990-00" },
  { assetType: "Other Leased Assets", accountCode: "10608990-00" },
  { assetType: "Other Machinery and Equipment", accountCode: "10605990-00" },
  { assetType: "Other Structures", accountCode: "10604990-00" },
  { assetType: "Other Transportation Equipment", accountCode: "10606990-00" },
  { assetType: "Parks, Plazas and Monuments", accountCode: "10603090-00" },
  { assetType: "Power Supply Systems", accountCode: "10603050-00" },
  { assetType: "Printing Equipment", accountCode: "10605120-00" },
  { assetType: "Road Networks", accountCode: "10603010-00" },
  { assetType: "School Buildings", accountCode: "10604020-00" },
  { assetType: "Seaport Systems", accountCode: "10603070-00" },
  { assetType: "Sewer Systems", accountCode: "10603030-00" },
  { assetType: "Slaughterhouses", accountCode: "10604050-00" },
  { assetType: "Sports Equipment", accountCode: "10605130-00" },
  { assetType: "Technical and Scientific Equipment", accountCode: "10605140-00" },
  { assetType: "Trains", accountCode: "10606020-00" },
  { assetType: "Volcanic Eruption Rescue Equipment", accountCode: "10605090-04" },
  { assetType: "Water Supply Systems", accountCode: "10603040-00" },
  { assetType: "Watercrafts", accountCode: "10606040-00" },
  { assetType: "Works of Arts and Archeological Specimens", accountCode: "10611020-00" },
  { assetType: "OTHERS", accountCode: "OTHERS" },
];

export const MASTER_CATALOG: Record<string, CatalogOption[]> = {
  ORGANIZATIONAL_CODE: [{ code: "350460000000", label: "350460000000" }],
  ASSET_TYPE: ASSET_TYPE_ACCOUNT_CODES.map((row) => ({
    code: row.accountCode,
    label: row.assetType,
    metadata: { accountCode: row.accountCode },
  })),
  ACCOUNT_CODE: ASSET_TYPE_ACCOUNT_CODES.map((row) => ({
    code: row.accountCode,
    label: `${row.accountCode} — ${row.assetType}`,
    metadata: { assetType: row.assetType },
  })),
  MODE_OF_ACQUISITION_CONVEYANCE: [
    "Constructed",
    "Donation",
    "Purchased",
    "Rented",
    "Transfer",
    "Usufruct",
    "Investment",
    "Lease",
    "Sublease",
    "OTHERS",
  ].map((label) => ({ label, code: label })),
  CURRENCY: [
    "AED",
    "ARS",
    "AUD",
    "BHD",
    "BND",
    "BRL",
    "CAD",
    "CHF",
    "CNY",
    "DKK",
    "EUR",
    "GBP",
    "HKD",
    "IDR",
    "INR",
    "JPY",
    "KRW",
    "KWD",
    "MXN",
    "MYR",
    "NOK",
    "NZD",
    "PHP",
    "PKR",
    "SAR",
    "SEK",
    "SGD",
    "SYP",
    "THB",
    "TWD",
    "USD",
    "VEB",
    "ZAR",
    "OTHERS",
  ].map((label) => ({ label, code: label })),
  MODE_OF_DISPOSAL: [
    "Consignment",
    "Demolition",
    "Depleted by Nature",
    "Donation",
    "Retirement",
    "Sale",
    "Trade-in",
    "Transfer of Ownership",
    "OTHERS",
  ].map((label) => ({ label, code: label })),
  POLICY_TYPE: [
    "Electronic Equipment",
    "Fire Insurance",
    "Fire w/ Allied Peril",
    "Floaters",
    "Industrial",
    "Machine Breakdown",
    "OTHERS",
  ].map((label) => ({ label, code: label })),
  ASSET_CONDITION: ["Serviceable", "Unserviceable", "Good", "Fair", "Poor", "Bad"].map((label) => ({
    label,
    code: label,
  })),
  STRUCTURE_MATERIAL: [
    "Bamboo",
    "Concrete Hollow Blocks",
    "Concrete Hollow Blocks with Wood",
    "Concrete Moment Frames",
    "Concrete Shear Walls",
    "Concrete Shear Walls and Frames",
    "Light Metal Frames",
    "Makeshift",
    "Precast Concrete Frames with Shear Walls",
    "Precast Concrete Tilt-up Walls",
    "Reinforced Concrete Moment Frames",
    "RMBW with Precast Concrete",
    "RMBW with Wood or Metal Deck",
    "Steel Braced Frames",
    "Steel Frames with Cast-in-place Concrete",
    "Steel Moment Frames",
    "Unreinforced Adobe or Stone Block",
    "Wood - Commercial and Industrial",
    "Wood - Light Frame",
    "OTHERS",
  ].map((label) => ({ label, code: label })),
  FLOOD_DEFENCES: [
    "Diversion Canal",
    "Elevated Structure",
    "Flood Barrier",
    "Flood way",
    "Retention Pond",
    "Water Pump",
    "OTHERS",
  ].map((label) => ({ label, code: label })),
  LAND_CLASSIFICATION: [
    "Agricultural Land",
    "Cemetery",
    "Commercial Property",
    "Foreshore Land",
    "Horticultural Land",
    "Industrial Land",
    "Mangrove Land",
    "Marsh Land",
    "Memorial Parks",
    "Mineral Lands",
    "National Integrated Protected Areas",
    "Non-Profit Cemetery",
    "Orchard",
    "Residential",
    "Socialized Housing",
    "Special Classes of Real Property",
    "Special Economic Zones",
    "Special Purpose Properties",
    "Timberland",
    "Tourism Development Areas",
    "Watershed",
    "OTHERS",
  ].map((label) => ({ label, code: label })),
  SECURITY_TYPE: [
    "Barbed wire",
    "Concrete wall",
    "Fenced wall",
    "Gated, with CCTV",
    "With Security Alarm System",
    "With Security Personnel",
    "OTHERS",
  ].map((label) => ({ label, code: label })),
};

export const MASTER_CATEGORY_META: Array<{
  id: string;
  label: string;
  description: string;
}> = [
  {
    id: "ORGANIZATIONAL_CODE",
    label: "Organizational Code",
    description: "UACS / agency organizational codes used on NARS records.",
  },
  {
    id: "ASSET_TYPE",
    label: "Asset Type",
    description: "COA PPE classification. Selecting a type loads its account code.",
  },
  {
    id: "ACCOUNT_CODE",
    label: "Account Code per Asset Type",
    description: "Chart of accounts codes linked to each asset type.",
  },
  {
    id: "REGIONS",
    label: "Region",
    description: "Philippine regions used in location information.",
  },
  {
    id: "PROVINCES",
    label: "Region & Province",
    description: "Provinces nested under each region.",
  },
  {
    id: "MODE_OF_ACQUISITION_CONVEYANCE",
    label: "Mode of Acquisition / Conveyance",
    description: "How the asset was acquired or conveyed.",
  },
  { id: "CURRENCY", label: "Currency", description: "Currencies for financial fields." },
  { id: "MODE_OF_DISPOSAL", label: "Mode of Disposal", description: "Disposal methods." },
  { id: "POLICY_TYPE", label: "Policy Type", description: "Insurance policy types." },
  { id: "ASSET_CONDITION", label: "Asset Condition", description: "Physical condition ratings." },
  {
    id: "STRUCTURE_MATERIAL",
    label: "Structure Material",
    description: "Construction / structural materials.",
  },
  { id: "FLOOD_DEFENCES", label: "Flood Defences", description: "Flood protection measures." },
  {
    id: "LAND_CLASSIFICATION",
    label: "Land Classification",
    description: "Land use / real property classification.",
  },
  { id: "SECURITY_TYPE", label: "Security Type", description: "Site security arrangements." },
];
